package protocol

import "testing"

func TestMessageTypeValuesRemainCompatible(t *testing.T) {
	tests := []struct {
		name string
		got  uint16
		want uint16
	}{
		{"HI", HI, 0},
		{"UUID", UUID, 1},
		{"CHILDUUIDREQ", CHILDUUIDREQ, 2},
		{"CHILDUUIDRES", CHILDUUIDRES, 3},
		{"MYINFO", MYINFO, 4},
		{"MYMEMO", MYMEMO, 5},
		{"SHELLREQ", SHELLREQ, 6},
		{"SHELLRES", SHELLRES, 7},
		{"SHELLCOMMAND", SHELLCOMMAND, 8},
		{"SHELLRESULT", SHELLRESULT, 9},
		{"SHELLEXIT", SHELLEXIT, 10},
		{"LISTENREQ", LISTENREQ, 11},
		{"LISTENRES", LISTENRES, 12},
		{"SSHREQ", SSHREQ, 13},
		{"SSHRES", SSHRES, 14},
		{"SSHCOMMAND", SSHCOMMAND, 15},
		{"SSHRESULT", SSHRESULT, 16},
		{"SSHEXIT", SSHEXIT, 17},
		{"SSHTUNNELREQ", SSHTUNNELREQ, 18},
		{"SSHTUNNELRES", SSHTUNNELRES, 19},
		{"FILESTATREQ", FILESTATREQ, 20},
		{"FILESTATRES", FILESTATRES, 21},
		{"FILEDATA", FILEDATA, 22},
		{"FILEERR", FILEERR, 23},
		{"FILEDOWNREQ", FILEDOWNREQ, 24},
		{"FILEDOWNRES", FILEDOWNRES, 25},
		{"SOCKSSTART", SOCKSSTART, 26},
		{"SOCKSTCPDATA", SOCKSTCPDATA, 27},
		{"SOCKSUDPDATA", SOCKSUDPDATA, 28},
		{"UDPASSSTART", UDPASSSTART, 29},
		{"UDPASSRES", UDPASSRES, 30},
		{"SOCKSTCPFIN", SOCKSTCPFIN, 31},
		{"SOCKSREADY", SOCKSREADY, 32},
		{"FORWARDTEST", FORWARDTEST, 33},
		{"FORWARDSTART", FORWARDSTART, 34},
		{"FORWARDREADY", FORWARDREADY, 35},
		{"FORWARDDATA", FORWARDDATA, 36},
		{"FORWARDFIN", FORWARDFIN, 37},
		{"BACKWARDTEST", BACKWARDTEST, 38},
		{"BACKWARDSTART", BACKWARDSTART, 39},
		{"BACKWARDSEQ", BACKWARDSEQ, 40},
		{"BACKWARDREADY", BACKWARDREADY, 41},
		{"BACKWARDDATA", BACKWARDDATA, 42},
		{"BACKWARDFIN", BACKWARDFIN, 43},
		{"BACKWARDSTOP", BACKWARDSTOP, 44},
		{"BACKWARDSTOPDONE", BACKWARDSTOPDONE, 45},
		{"CONNECTSTART", CONNECTSTART, 46},
		{"CONNECTDONE", CONNECTDONE, 47},
		{"NODEOFFLINE", NODEOFFLINE, 48},
		{"NODEREONLINE", NODEREONLINE, 49},
		{"UPSTREAMOFFLINE", UPSTREAMOFFLINE, 50},
		{"UPSTREAMREONLINE", UPSTREAMREONLINE, 51},
		{"SHUTDOWN", SHUTDOWN, 52},
		{"HEARTBEAT", HEARTBEAT, 53},
	}

	for _, tc := range tests {
		if tc.got != tc.want {
			t.Fatalf("%s = %d, want %d", tc.name, tc.got, tc.want)
		}
	}
}
